In [387]:
# import libraries 
import pandas as pd
import numpy as np
from dateutil import parser
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [388]:
pd.set_option('display.float', lambda x: f'{x:.2f}')

Month4:
Week 3:

Assignment: Nigeria Jiji Housing Marketplace Data Analysis
Title:
Market Analysis of Housing Sales on Jiji.ng Using Python
Overview
You will analyze real-world housing listings from the Jiji Nigeria Marketplace.
Your task is to extract listing data using Python from Jiji’s public API, clean and preprocess the data, perform exploratory data analysis (EDA), visualize the trends, and generate business insights and recommendations.
This assignment will help you practice:
Working with APIs


JSON data extraction


Data cleaning and transformation


Exploratory data analysis


Visualization


Business insight generation



Task 1: Data Extraction
Objective:
Extract housing data from the Jiji API and convert it into a clean DataFrame.
API Endpoint to Use:
https://jiji.ng/api_web/v1/listing?slug=houses-apartments-for-sale&page=1&webp=true

Requirements:
Write a Python script to send a GET request to the endpoint.


Use the requests library.


Extract the following key fields from each advert object:


title


region, region_name, region_parent_name


price_title (formatted price)


attrs fields


Property size


Bedrooms


Bathrooms


Furnishing status


is_boost (enterprise/diamond)


Convert the extracted data into a Pandas DataFrame.


Save the dataset locally as jiji_housing_raw.csv.



Task 2: Data Cleaning
Objective:
Prepare the dataset for reliable analysis.
Questions to Guide Cleaning:
Missing Values


Which columns have missing values?


How will you handle missing property size, bedrooms, bathrooms, or furnishing?


Price Cleaning


Convert the price from strings like “₦ 85,500,000” to float (85500000.00)


Are there outlier prices that should be removed?


Categorical Cleaning


Standardize region, region_name, region_parent_name.


Convert furnishing type to consistent categories
 (e.g., Furnished / Semi-furnished / Unfurnished / Unknown)


Attributes Extraction


Extract values for Bedrooms, Bathrooms, Property size from the attrs JSON list.


Remove duplicates


Look for duplicate titles or identical rows.


Save cleaned dataset as:
 jiji_housing_cleaned.csv



Task 3: Exploratory Data Analysis (EDA)
Objective:
Understand the structure, patterns, and distribution of the Nigerian housing marketplace on Jiji.
Your EDA Should Answer These Questions:
Price Analysis


What is the average house price in Nigeria?


Which state has the highest and lowest mean property price?


Property Size & Features


What is the distribution of property sizes?


Do houses with more bedrooms/bathrooms cost significantly more?


Regional Trends


Which regions have the highest number of listings?


Which regions dominate premium property sales?


Furnishing Analysis


Are furnished apartments more expensive on average?


Listing Type


Do boosted/enterprise listings have higher prices?



Task 4 — Visualization
Create the following visualizations (using Streamlit):
KPI SECTION (Top of Dashboard)
Q1. How many houses are listed in the dataset?
 Display the total number of house listings as a KPI.
Q2. What is the average price of houses in Nigeria?
Display the mean house price (₦) as a KPI.
Q3. Which house region appears most frequently in the listings?
 Display the most common house region as a KPI.
Q4. What percentage of houses are furnished?
 Display the percentage of furnished houses as a KPI.

Required Charts:
Bar Chart: Number of listings per state


Bar Chart: Average price per state


Histogram: Distribution of property prices


Boxplot: Price by number of bedrooms


Scatter Plot: Property size vs. price


Pie Chart: Furnishing type distribution


Heatmap: Correlation of numeric variables (price, size, bedrooms, bathrooms)


Use:
Matplotlib


Seaborn


Plotly



Task 5: Summary of Findings 
Rewrite your findings by answering the following:
Which states have the highest-priced listings?


Which states are the most affordable?


Do furnished homes consistently cost more than unfurnished ones?


How strongly do bedrooms, bathrooms, or property size influence price?


Are boosted (Enterprise) listings typically more expensive?


What property types attract premium pricing?


What patterns exist in Lagos vs Abuja vs other regions?


Your summary should be 6–10 lines.

Task 6: Business Insights & Recommendations
Provide a 5–7 line business-focused insight summary, answering:
Which housing type or feature performs best overall on Jiji?


Which state contributes the most revenue potential?


Which states underperform?


Which period (if using timestamps) records the highest listing activity?


What strategies can improve sales in low-performing regions?


What can sellers do to increase listing visibility and pricing power?



Final Deliverables
Upload the following:
Python notebook (.ipynb)


Raw dataset (CSV)


Cleaned dataset (CSV)


Visualizations (inside notebook)


Insight & recommendation section

In [389]:
# Load a csv file on pandas
#Load csv file dataset on pandas 

df = pd.read_csv("data/jiji_housing_raw.csv")

df

,title,property_size,bedrooms,bathrooms,furnishing,region,region_name,region_parent_name,is_boost,price
0,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,"₦ 220,000,000"
1,"4bdrm House in Ajah, Lekki, Abraham Adesanya E...",1000,4,4,unfurnished,"Ajah, Abraham Adesanya Estate",Abraham Adesanya Estate,Ajah,premium,"₦ 140,000,000"
2,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,"₦ 180,000,000"
3,"Furnished 2bdrm Apartment in Twin Estate, Abij...",150,2,4,furnished,"Ibeju, Abijo",Abijo,Ibeju,False,"₦ 75,000,000"
4,5bdrm Duplex in Lekki for sale,350,5,5,unfurnished,"Lagos State, Lekki",Lekki,Lagos State,premium,"₦ 550,000,000"
...,...,...,...,...,...,...,...,...,...,...
1995,4bdrm Duplex in Lekki Scheme 2 for sale,350,4,5,unfurnished,"Lekki, Lekki Phase 2",Lekki Phase 2,Lekki,enterprise,"₦ 130,000,000"
1996,"Furnished 5bdrm Duplex in Chevron, Lekki for sale",150,5,6,furnished,"Lekki, Chevron",Chevron,Lekki,enterprise,"₦ 450,000,000"
1997,5bdrm Duplex in Maryland for sale,500,5,6,unfurnished,"Lagos State, Maryland",Maryland,Lagos State,enterprise,"₦ 1,200,000,000"
1998,4bdrm Duplex in Ikoyi for sale,100,4,4,unfurnished,"Lagos State, Ikoyi",Ikoyi,Lagos State,enterprise,"₦ 1,000,000,000"
1999,5bdrm Duplex in Ologolo for sale,100,5,5,unfurnished,"Lekki, Ologolo",Ologolo,Lekki,enterprise,"₦ 500,000,000"

In [390]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               2000 non-null   str
 1   property_size       2000 non-null   int64
 2   bedrooms            2000 non-null   int64
 3   bathrooms           2000 non-null   int64
 4   furnishing          2000 non-null   str
 5   region              2000 non-null   str
 6   region_name         2000 non-null   str
 7   region_parent_name  1996 non-null   str
 8   is_boost            2000 non-null   str
 9   price               2000 non-null   str
dtypes: int64(3), str(7)
memory usage: 379.3 KB

In [391]:
#Missing Values

df.isnull().sum()

title                 0
property_size         0
bedrooms              0
bathrooms             0
furnishing            0
region                0
region_name           0
region_parent_name    4
is_boost              0
price                 0
dtype: int64

In [392]:
# I dropped all the null values in the dataset since its just 4 data out of 2000 dataset. 

df.dropna(inplace=True)

# Rechecking the null values in the dataset

df.isnull().sum()

title                 0
property_size         0
bedrooms              0
bathrooms             0
furnishing            0
region                0
region_name           0
region_parent_name    0
is_boost              0
price                 0
dtype: int64

In [393]:
df.shape

(1996, 10)

In [394]:
df.columns

Index(['title', 'property_size', 'bedrooms', 'bathrooms', 'furnishing',
       'region', 'region_name', 'region_parent_name', 'is_boost', 'price'],
      dtype='str')

In [395]:
#Data cleaning 
#Question: Standardize region, region_name, region_parent_name.

df.rename(columns={
    "title" : "Title" , 
    "property_size" : "Property Size" ,
    "bedrooms" : "Bedrooms" ,
    "bathrooms" : "Bathrooms" ,
    "furnishing" : "Furnishing" ,
    "region" : "Region" ,
    "region_name" : "Region Name" ,
    "region_parent_name" : "Region Parent Name",
    "is_boost" : "Is Boost",
    "price" : "Price"
} , inplace=True)

df.head(3)

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,"₦ 220,000,000"
1,"4bdrm House in Ajah, Lekki, Abraham Adesanya E...",1000,4,4,unfurnished,"Ajah, Abraham Adesanya Estate",Abraham Adesanya Estate,Ajah,premium,"₦ 140,000,000"
2,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,"₦ 180,000,000"

In [396]:
#check for unique values in each colunms

print(df["Title"].unique())
print(df["Property Size"].unique())
print(df["Bedrooms"].unique())
print(df["Bathrooms"].unique())
print(df["Furnishing"].unique())
print(df["Region"].unique())
print(df["Region Name"].unique())
print(df["Region Parent Name"].unique())
print(df["Is Boost"].unique())
print(df["Price"].unique())

<ArrowStringArray>
[                         '4bdrm Townhouse/Terrace in Gaduwa for sale',
        '4bdrm House in Ajah, Lekki, Abraham Adesanya Estate for sale',
            'Furnished 2bdrm Apartment in Twin Estate, Abijo for sale',
                                      '5bdrm Duplex in Lekki for sale',
                           '3bdrm Block of Flats in Surulere for sale',
 'Furnished 1bdrm Block of Flats in Molosho Estate, Gberigbe for sale',
                                  '3bdrm Apartment in Gaduwa for sale',
       '2bdrm Block of Flats in Brains Ams Hammers, Gwarinpa for sale',
               '5bdrm House in Magodo, GRA Phase 2 Shangisha for sale',
                           '2bdrm Apartment in Lekki Phase 1 for sale',
 ...
                        '3bdrm Duplex in Secured Area, Fagba for sale',
                          'Furnished 5bdrm Duplex in Chevron for sale',
                      '6bdrm Duplex in Estate, Magodo Isheri for sale',
                                   '2bdrm Apartment in Ebute for sale',
                                        '4bdrm Duplex in Ojo for sale',
               'Furnished 5bdrm Duplex in Magodo Gra Phase 2 for sale',
                         '7bdrm House in No Estate, Gberigbe for sale',
                             '4bdrm Duplex in Lekki Scheme 2 for sale',
                   'Furnished 5bdrm Duplex in Chevron, Lekki for sale',
                                   '5bdrm Duplex in Maryland for sale']
Length: 1447, dtype: str
[ 300 1000  150  350  580  252  160  225  600  464  870  648  380  500
  450  460 2500  700  100  220  250 2100 2120  912  560  650  200 2074
  400  800  635   55 1200  750   10   50 2000   15 1115 1350  310  465
  410 1500  550  790  360  475  839 3000  780  320  510  470  629  180
  900  502  501  575  639  540  270   24  909   60 1800 5000  420  135
  950  920  120  430  329  943 4000 1150  445 1346 1400 3700 1300  222
 1119 1277 1100  986  850   12 1020  989  280  114 1016  333  702 2200
 4100  230  190   80   90  130  260  240  480   30  520  530 1986  287
  276  298  279  456  830  312  389  289  546 1470  278  656  290  140
 4900  620 1185  760 1492 1700  557 1450  284 4200  630  330  675  463
  383  742  210   88  402  325  209  730   25 1600 1180  910  324 1030
  913   40   41  739  525  108  390  248  412  652  326  347  640  649
  124  170  323 3600  930 2700 1900  680  770   33 1002 1375  245  411
  515  690  625]
[ 4  2  5  3  1  9 19 12 20  6  7 10  8 18 13 11 15 16 17]
[ 4  5  3  1  2 10 19  8  6 20  7 18 12 13 11  9 14 15]
<ArrowStringArray>
['unfurnished', 'furnished', 'semi-furnished']
Length: 3, dtype: str
<ArrowStringArray>
[            'Abuja (FCT), Gaduwa',   'Ajah, Abraham Adesanya Estate',
                    'Ibeju, Abijo',              'Lagos State, Lekki',
           'Lagos State, Surulere',               'Ikorodu, Gberigbe',
           'Abuja (FCT), Gwarinpa',   'Magodo, GRA Phase 2 Shangisha',
            'Lekki, Lekki Phase 1',                    'Lekki, Ikota',
 ...
     'Delta State, Oshimili North',                   'Ikeja, Alausa',
            'Ogba, Oke-Ira / Ogba',           'Abuja (FCT), Mararaba',
                'Alimosho, Akesan',          'Ekiti State, Ado Ekiti',
                'Ipaja, Boys Town',                   'Epe, Epe Road',
 'Ilupeju, Ikorodu Road / Ilupeju',                'Lagos State, Ojo']
Length: 271, dtype: str
<ArrowStringArray>
[                 'Gaduwa', 'Abraham Adesanya Estate',
                   'Abijo',                   'Lekki',
                'Surulere',                'Gberigbe',
                'Gwarinpa',   'GRA Phase 2 Shangisha',
           'Lekki Phase 1',                   'Ikota',
 ...
          'Oshimili North',                  'Alausa',
          'Oke-Ira / Ogba',                'Mararaba',
                  'Akesan',               'Ado Ekiti',
               'Boys Town',                'Epe Road',
  'Ikorodu Road / Ilupeju',                     'Ojo']
Length: 271, dtype: str
<ArrowStringArray>
[       'Abuja (FCT)',               'Ajah',              'Ibeju',
        'Lagos State',            'Ikorodu',             'Magodo',
              'Lekki',        'Delta State',              'Ikeja',
            'Gbagada',  'Cross River State',        'Enugu State',
      'Ikotun/Igando',     'Lugbe District',             'Ibadan',
          'Imo State',             'Ejigbo',           'Surulere',
         'Ogun State',               'Wuse',           'Gwarinpa',
              'Isolo',              'Ojodu',          'Edo State',
         'Osun State',          'Oyo State',       'Rivers State',
            'Katampe',    'Akwa Ibom State',             'Egbeda',
              'Ogudu',              'Ikoyi',      'Port-Harcourt',
           'Maryland',             'Kosofe',        'Kwara State',
           'Alimosho',       'Apo District',       'Kaduna State',
         'Egbe/Idimu',             'Gwagwa',              'Agege',
         'Ondo State',       'Jigawa State',    'Victoria Island',
              'Ipaja',       'Amuwo-Odofin',               'Ogba',
             'Sagamu',            'Garki 1',               'Jiwa',
              'Bwari', 'Lagos Island (Eko)',             'Oshodi',
             'Mushin',            'Shomolu',         'Abia State',
       'Ifako-Ijaiye',        'Ekiti State',                'Epe',
            'Ilupeju']
Length: 61, dtype: str
<ArrowStringArray>
['premium', 'False', 'enterprise', 'diamond', 'vip_gold', 'vip', 'basic']
Length: 7, dtype: str
<ArrowStringArray>
['₦ 220,000,000', '₦ 140,000,000', '₦ 180,000,000',  '₦ 75,000,000',
 '₦ 550,000,000', '₦ 280,000,000',  '₦ 26,000,000', '₦ 100,000,000',
  '₦ 37,000,000', '₦ 600,000,000',
 ...
 '₦ 235,000,000',  '₦ 42,750,000', '₦ 252,000,000', '₦ 930,000,000',
 '₦ 225,000,000',  '₦ 33,500,000',  '₦ 87,500,000',  '₦ 29,000,000',
  '₦ 14,800,000', '₦ 243,000,000']
Length: 227, dtype: str

In [397]:
# Price cleaning 
# Question: Convert the price from strings like “₦ 85,500,000” to float (85500000.00)

df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("₦", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)
df["Price"]

0       220000000.00
1       140000000.00
2       180000000.00
3        75000000.00
4       550000000.00
            ...
1995    130000000.00
1996    450000000.00
1997   1200000000.00
1998   1000000000.00
1999    500000000.00
Name: Price, Length: 1996, dtype: float64

In [398]:
#Are there outlier prices that should be removed?
#exclude an outliers in dataframe

Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)
Q1
Q3
IQR = Q3 -Q1
IQR

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = ( df['Price'] < lower_bound) | ( df['Price'] > upper_bound)

print(outliers.sum())

196

In [399]:
# Create a new df after removing price column outliers 

new_df = df[
    (df['Price'] > lower_bound) & ( df['Price'] < upper_bound)
] 

new_df

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,220000000.00
1,"4bdrm House in Ajah, Lekki, Abraham Adesanya E...",1000,4,4,unfurnished,"Ajah, Abraham Adesanya Estate",Abraham Adesanya Estate,Ajah,premium,140000000.00
2,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,180000000.00
3,"Furnished 2bdrm Apartment in Twin Estate, Abij...",150,2,4,furnished,"Ibeju, Abijo",Abijo,Ibeju,False,75000000.00
4,5bdrm Duplex in Lekki for sale,350,5,5,unfurnished,"Lagos State, Lekki",Lekki,Lagos State,premium,550000000.00
...,...,...,...,...,...,...,...,...,...,...
1994,2bdrm Apartment in Ikate for sale,350,2,2,unfurnished,"Lekki, Ikate",Ikate,Lekki,enterprise,200000000.00
1995,4bdrm Duplex in Lekki Scheme 2 for sale,350,4,5,unfurnished,"Lekki, Lekki Phase 2",Lekki Phase 2,Lekki,enterprise,130000000.00
1996,"Furnished 5bdrm Duplex in Chevron, Lekki for sale",150,5,6,furnished,"Lekki, Chevron",Chevron,Lekki,enterprise,450000000.00
1998,4bdrm Duplex in Ikoyi for sale,100,4,4,unfurnished,"Lagos State, Ikoyi",Ikoyi,Lagos State,enterprise,1000000000.00
1999,5bdrm Duplex in Ologolo for sale,100,5,5,unfurnished,"Lekki, Ologolo",Ologolo,Lekki,enterprise,500000000.00

In [400]:
# Question: Convert furnishing type to consistent categories (e.g., Furnished / Semi-furnished / Unfurnished / Unknown)

new_df["Furnishing"] = (
    new_df["Furnishing"]
    .str.lower()
    .replace({
        "semi furnished": "Semi-Furnished",
        "furnished": "Furnished",
        "unfurnished": "Unfurnished"
    })
)

new_df

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,Unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,220000000.00
1,"4bdrm House in Ajah, Lekki, Abraham Adesanya E...",1000,4,4,Unfurnished,"Ajah, Abraham Adesanya Estate",Abraham Adesanya Estate,Ajah,premium,140000000.00
2,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,Unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,180000000.00
3,"Furnished 2bdrm Apartment in Twin Estate, Abij...",150,2,4,Furnished,"Ibeju, Abijo",Abijo,Ibeju,False,75000000.00
4,5bdrm Duplex in Lekki for sale,350,5,5,Unfurnished,"Lagos State, Lekki",Lekki,Lagos State,premium,550000000.00
...,...,...,...,...,...,...,...,...,...,...
1994,2bdrm Apartment in Ikate for sale,350,2,2,Unfurnished,"Lekki, Ikate",Ikate,Lekki,enterprise,200000000.00
1995,4bdrm Duplex in Lekki Scheme 2 for sale,350,4,5,Unfurnished,"Lekki, Lekki Phase 2",Lekki Phase 2,Lekki,enterprise,130000000.00
1996,"Furnished 5bdrm Duplex in Chevron, Lekki for sale",150,5,6,Furnished,"Lekki, Chevron",Chevron,Lekki,enterprise,450000000.00
1998,4bdrm Duplex in Ikoyi for sale,100,4,4,Unfurnished,"Lagos State, Ikoyi",Ikoyi,Lagos State,enterprise,1000000000.00
1999,5bdrm Duplex in Ologolo for sale,100,5,5,Unfurnished,"Lekki, Ologolo",Ologolo,Lekki,enterprise,500000000.00

In [401]:
new_df["Region Parent Name"].unique()

<ArrowStringArray>
[       'Abuja (FCT)',               'Ajah',              'Ibeju',
        'Lagos State',            'Ikorodu',             'Magodo',
              'Lekki',        'Delta State',              'Ikeja',
            'Gbagada',  'Cross River State',        'Enugu State',
      'Ikotun/Igando',     'Lugbe District',             'Ibadan',
          'Imo State',             'Ejigbo',           'Surulere',
         'Ogun State',           'Gwarinpa',              'Isolo',
              'Ojodu',          'Edo State',         'Osun State',
          'Oyo State',       'Rivers State',    'Akwa Ibom State',
             'Egbeda',              'Ogudu',      'Port-Harcourt',
           'Maryland',             'Kosofe',        'Kwara State',
           'Alimosho',            'Katampe',       'Apo District',
       'Kaduna State',              'Ikoyi',         'Egbe/Idimu',
               'Wuse',             'Gwagwa',              'Agege',
         'Ondo State',       'Jigawa State',    'Victoria Island',
              'Ipaja',       'Amuwo-Odofin',               'Ogba',
             'Sagamu',            'Garki 1',               'Jiwa',
              'Bwari', 'Lagos Island (Eko)',             'Oshodi',
             'Mushin',            'Shomolu',         'Abia State',
       'Ifako-Ijaiye',        'Ekiti State',                'Epe',
            'Ilupeju']
Length: 61, dtype: str

In [402]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Ajah', 'Ibeju', 'Ikorodu', 'Magodo', 'Lekki', 'Delta State', 'Ikeja', 'Gbagada',
                                                                     'Ikotun/Igando', 'Ejigbo','Surulere', 'Isolo', 'Ojodu', 'Egbeda', 'Ogudu',
                                                                     'Maryland', 'Kosofe', 'Alimosho', 'Ikoyi', 'Egbe/Idimu', 'Agege', 'Ondo State',
                                                                     'Victoria Island', 'Ipaja', 'Amuwo-Odofin', 'Ogba', 'Lagos Island (Eko)','Oshodi',
                                                                     'Mushin', 'Shomolu', 'Ifako-Ijaiye','Ilupeju', 'Epe'], 'Lagos State')

new_df['Region Parent Name'].unique()

<ArrowStringArray>
[      'Abuja (FCT)',       'Lagos State', 'Cross River State',
       'Enugu State',    'Lugbe District',            'Ibadan',
         'Imo State',        'Ogun State',          'Gwarinpa',
         'Edo State',        'Osun State',         'Oyo State',
      'Rivers State',   'Akwa Ibom State',     'Port-Harcourt',
       'Kwara State',           'Katampe',      'Apo District',
      'Kaduna State',              'Wuse',            'Gwagwa',
      'Jigawa State',            'Sagamu',           'Garki 1',
              'Jiwa',             'Bwari',        'Abia State',
       'Ekiti State']
Length: 28, dtype: str

In [403]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Lugbe District', 'Katampe', 'Apo District','Wuse',
                                                                     'Gwagwa', 'Gwarinpa', 'Garki 1', 'Jiwa', 'Bwari',  ], 'Abuja (FCT)')

new_df['Region Parent Name'].unique()

<ArrowStringArray>
[      'Abuja (FCT)',       'Lagos State', 'Cross River State',
       'Enugu State',            'Ibadan',         'Imo State',
        'Ogun State',         'Edo State',        'Osun State',
         'Oyo State',      'Rivers State',   'Akwa Ibom State',
     'Port-Harcourt',       'Kwara State',      'Kaduna State',
      'Jigawa State',            'Sagamu',        'Abia State',
       'Ekiti State']
Length: 19, dtype: str

In [404]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Ibadan'], 'Oyo State')


new_df['Region Parent Name'].unique()

<ArrowStringArray>
[      'Abuja (FCT)',       'Lagos State', 'Cross River State',
       'Enugu State',         'Oyo State',         'Imo State',
        'Ogun State',         'Edo State',        'Osun State',
      'Rivers State',   'Akwa Ibom State',     'Port-Harcourt',
       'Kwara State',      'Kaduna State',      'Jigawa State',
            'Sagamu',        'Abia State',       'Ekiti State']
Length: 18, dtype: str

In [405]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Sagamu'], 'Ogun State')

new_df['Region Parent Name'].unique()

<ArrowStringArray>
[      'Abuja (FCT)',       'Lagos State', 'Cross River State',
       'Enugu State',         'Oyo State',         'Imo State',
        'Ogun State',         'Edo State',        'Osun State',
      'Rivers State',   'Akwa Ibom State',     'Port-Harcourt',
       'Kwara State',      'Kaduna State',      'Jigawa State',
        'Abia State',       'Ekiti State']
Length: 17, dtype: str

In [406]:
# Question: Remove duplicates;Look for duplicate titles or identical rows.
new_df.drop_duplicates(inplace=True)
new_df

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,Unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,220000000.00
1,"4bdrm House in Ajah, Lekki, Abraham Adesanya E...",1000,4,4,Unfurnished,"Ajah, Abraham Adesanya Estate",Abraham Adesanya Estate,Lagos State,premium,140000000.00
2,4bdrm Townhouse/Terrace in Gaduwa for sale,300,4,4,Unfurnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),premium,180000000.00
3,"Furnished 2bdrm Apartment in Twin Estate, Abij...",150,2,4,Furnished,"Ibeju, Abijo",Abijo,Lagos State,False,75000000.00
4,5bdrm Duplex in Lekki for sale,350,5,5,Unfurnished,"Lagos State, Lekki",Lekki,Lagos State,premium,550000000.00
...,...,...,...,...,...,...,...,...,...,...
1994,2bdrm Apartment in Ikate for sale,350,2,2,Unfurnished,"Lekki, Ikate",Ikate,Lagos State,enterprise,200000000.00
1995,4bdrm Duplex in Lekki Scheme 2 for sale,350,4,5,Unfurnished,"Lekki, Lekki Phase 2",Lekki Phase 2,Lagos State,enterprise,130000000.00
1996,"Furnished 5bdrm Duplex in Chevron, Lekki for sale",150,5,6,Furnished,"Lekki, Chevron",Chevron,Lagos State,enterprise,450000000.00
1998,4bdrm Duplex in Ikoyi for sale,100,4,4,Unfurnished,"Lagos State, Ikoyi",Ikoyi,Lagos State,enterprise,1000000000.00
1999,5bdrm Duplex in Ologolo for sale,100,5,5,Unfurnished,"Lekki, Ologolo",Ologolo,Lagos State,enterprise,500000000.00

In [407]:
new_df.info()

<class 'pandas.DataFrame'>
Index: 1753 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               1753 non-null   str
 1   Property Size       1753 non-null   int64
 2   Bedrooms            1753 non-null   int64
 3   Bathrooms           1753 non-null   int64
 4   Furnishing          1753 non-null   str
 5   Region              1753 non-null   str
 6   Region Name         1753 non-null   str
 7   Region Parent Name  1753 non-null   str
 8   Is Boost            1753 non-null   str
 9   Price               1753 non-null   float64
dtypes: float64(1), int64(3), str(6)
memory usage: 327.2 KB

In [408]:
new_df.isnull().sum()

Title                 0
Property Size         0
Bedrooms              0
Bathrooms             0
Furnishing            0
Region                0
Region Name           0
Region Parent Name    0
Is Boost              0
Price                 0
dtype: int64

In [409]:
# Question: Save cleaned dataset as:  jiji_housing_cleaned.csv

new_df.to_csv("data/jiji_housing_cleaned.csv", index=False)

In [410]:
#Task 3: Exploratory Data Analysis (EDA)
# 1. Price Analysis
#Question: What is the average house price in Nigeria?

avg_house_price = round(new_df["Price"].mean(), 2)


print(f"Average House Price:", avg_house_price)

Average House Price: 300616913.86

In [411]:
#Question: Which state has the highest and lowest mean property price?

state_property_price = (
    new_df.groupby("Region Parent Name")["Price"]
    .mean()
    .sort_values(ascending=False)
)
print("State With Highest Mean Property Price:")
print(state_property_price.head())

print("\nState With Lowest Mean Property Price:")
print(state_property_price.tail())

State With Highest Mean Property Price:
Region Parent Name
Jigawa State    870000000.00
Lagos State     334950614.37
Abuja (FCT)     307456521.74
Rivers State    243571428.57
Port-Harcourt   221125000.00
Name: Price, dtype: float64

State With Lowest Mean Property Price:
Region Parent Name
Osun State          82000000.00
Cross River State   60000000.00
Kwara State         31875000.00
Akwa Ibom State     19000000.00
Ekiti State         15000000.00
Name: Price, dtype: float64

In [412]:
# 2. Property Size & Features
# Question: What is the distribution of property sizes?

new_df["Property Size"].value_counts().head(10)

Property Size
500     301
300     158
600     136
400     113
1000    112
450     107
250      92
350      79
100      71
200      55
Name: count, dtype: int64

In [413]:
## Question: Do houses with more bedrooms/bathrooms cost significantly more?
region_counts = new_df["Region Name"].value_counts()

print(region_counts.head(10))

Region Name
Lekki Phase 1    85
Chevron          83
Ikota            76
Lekki            52
Ikate            45
Life Camp        37
Akobo            35
GRA Phase 1      34
Ado / Ajah       32
Akala Express    30
Name: count, dtype: int64

In [414]:
# 4. Furnishing Analysis
# Question: Are furnished apartments more expensive on average?

furnishing_aprt = (
    new_df.groupby("Furnishing")["Price"]
    .mean()
    .sort_values(ascending=False)
)

print(furnishing_aprt)

Furnishing
Furnished        324843154.76
semi-furnished   313788429.75
Unfurnished      280778509.85
Name: Price, dtype: float64

In [415]:
# 5. Listing Type
# Do boosted/enterprise listings have higher prices?
boost_price = (
    new_df.groupby("Is Boost")["Price"]
    .mean().sort_values(ascending=False)
)

print(boost_price)

Is Boost
enterprise   330325990.94
diamond      284976850.61
vip_gold     202666666.67
False        180528888.89
premium      179454545.45
vip          177500000.00
basic         89600000.00
Name: Price, dtype: float64

In [416]:
#Correlation Analysis
corr = new_df[
    [
        "Price",
        "Property Size",
        "Bedrooms",
        "Bathrooms"
    ]
].corr()

corr

               Price  Property Size  Bedrooms  Bathrooms
Price           1.00           0.10      0.18       0.13
Property Size   0.10           1.00      0.17       0.09
Bedrooms        0.18           0.17      1.00       0.82
Bathrooms       0.13           0.09      0.82       1.00

In [417]:
new_df.to_csv("data/cleaned_nigeria_housing_dataset.csv", index=False)

Task 5: Summary of Findings Rewrite your findings by answering the following: Which states have the highest-priced listings?

Which states are the most affordable?

Do furnished homes consistently cost more than unfurnished ones?

How strongly do bedrooms, bathrooms, or property size influence price?

Are boosted (Enterprise) listings typically more expensive?

What property types attract premium pricing?

What patterns exist in Lagos vs Abuja vs other regions?

Your summary should be 6–10 lines.

Task 6: Business Insights & Recommendations Provide a 5–7 line business-focused insight summary, answering: Which housing type or feature performs best overall on Jiji?

Which state contributes the most revenue potential?

Which states underperform?

Which period (if using timestamps) records the highest listing activity?

What strategies can improve sales in low-performing regions?

What can sellers do to increase listing visibility and pricing power?